server:
  port: 8081  # Port pour le service client

spring:
  application:
    name: SERVICE-CLIENT  # Nom du service tel qu'il apparaîtra dans Eureka
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clientservicedb?createDatabaseIfNotExist=true
    username: "root"
    password: ""
  jpa:
    hibernate:
      ddl-auto: update  # Crée ou met à jour automatiquement le schéma de la base
      show-sql: true    # Affiche les requêtes SQL générées

# Configuration Eureka (à ajouter)
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # URL du serveur Eureka
  instance:
    prefer-ip-address: true  # Utilise l'adresse IP plutôt que le nom d'hôte